# Supabase 設定
SUPABASE_URL=https://ooxswwmexulfkgnnqsqb.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9veHN3d21leHVsZmtnbm5xc3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDM1ODAsImV4cCI6MjA3MTI3OTU4MH0.issIBPShVMyyymB4HLRf1EB232ig40NhOY8vxxFpfsU
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9veHN3d21leHVsZmtnbm5xc3FiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTcwMzU4MCwiZXhwIjoyMDcxMjc5NTgwfQ.yo_n-cHcfCYFBGb7TQdZFAJBbepq2qHTT57EbqAKogY
SUPABASE_BUCKET=CRS_Schedule

